documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/*.md'
      - any-glob-to-any-file: 'docs/*.rst'
      - any-glob-to-any-file: '*.md'
python:
  - changed-files:
      - any-glob-to-any-file: 'gaphas/**/*.py'
skip-changelog:
  - changed-files:
      - any-glob-to-any-file: '.pre-commit-config.yaml'
      - any-glob-to-any-file: '.all-contributorsrc'
