version: 2
formats: all
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
  - libgirepository1.0-dev
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs