name: build
on:
  push:

jobs:
  build:
    name: GTK 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Build
        run: docker build -f .github/Dockerfile-gtk4 .
