name: PR Labeler
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      pull-requests: write  # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io

      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
