name: PR Labeler
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      pull-requests: write  # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
