name: Release Drafter

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
